# Python 3.8 기반 이미지 사용
FROM python:3.8-slim

# 컨테이너 내부 작업 디렉토리 설정
WORKDIR /webtest

# 필요한 파일 복사
COPY requirements.txt requirements.txt
COPY . .

# 필요한 라이브러리 설치
RUN pip install --no-cache-dir -r requirements.txt

# Flask가 사용할 포트 열기
EXPOSE 5002

# Flask 실행
CMD ["python", "makeweb.py"]
